# Generated by Django 3.0.3 on 2020-03-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='portada',
            field=models.ImageField(null=True, upload_to='portada'),
        ),
    ]
