# Generated by Django 3.0.3 on 2020-03-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20200327_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada'),
        ),
    ]
