# Generated by Django 3.0.3 on 2020-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
        ('libros', '0004_auto_20200328_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='autor',
            field=models.ManyToManyField(to='autores.Autores'),
        ),
    ]
