# Generated by Django 3.0.3 on 2020-04-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libros_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libros',
            options={'ordering': ['id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
