# Generated by Django 3.0.3 on 2020-04-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20200401_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
