# Generated by Django 3.0.3 on 2020-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autores',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.AlterField(
            model_name='autores',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
