# Generated by Django 3.0.3 on 2020-04-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectores', '0002_auto_20200330_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectores',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
