# Generated by Django 3.0.3 on 2020-04-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectores', '0003_auto_20200403_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
