# Generated by Django 3.0.3 on 2020-04-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectores', '0004_prestamos_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='fecha_prestame',
            new_name='fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='stock',
        ),
    ]
